Repository jenkinsci/job-dsl-plugin, pull requests merged in 2023-03, with the labels that each got.

#1266 Enable Dependabot
  .github/dependabot.yml
Labels: internal

#1268 Add Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: internal

#1274 Disable Dependabot PRs for Bootstrap 4 and later
  .github/dependabot.yml
Labels: skip-changelog

#1275 Disable Dependabot PRs for Spock 2.x and later
  .github/dependabot.yml
Labels: skip-changelog

#1267 Add Windows to build/test matrix
  Jenkinsfile
Labels: test

#1277 Upgrade CodeNarc from 1.2 to 1.6.1
  .github/dependabot.yml
  config/codenarc/rules.groovy
  job-dsl-ast/pom.xml
  job-dsl-core/pom.xml
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/doc/ApiDocGenerator.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/ScmContext.groovy
  job-dsl-plugin/pom.xml
  job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/GlobalJobDslSecurityConfiguration.groovy
  job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/ExecuteDslScriptsSpec.groovy
  job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/JenkinsJobManagementSpec.groovy
  pom.xml
Labels: test

#1279 Downgrade to JUnit 4
  pom.xml
Labels: test

#1281 Enable Release Drafter
  .github/CODEOWNERS
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  RELEASING.md
  docs/Home.md
  pom.xml
Labels: internal

#1280 Restore version selector
  RELEASING.md
  job-dsl-plugin/copyData.groovy
  job-dsl-plugin/pom.xml
  job-dsl-plugin/src/main/hbs/root.hbs
  job-dsl-plugin/src/main/js/components/App.js
  job-dsl-plugin/src/main/less/main.less
  job-dsl-plugin/webpack.dev.js
Labels: internal

#1282 Restore automated wiki updates
  .github/workflows/wiki.yml
  RELEASING.md
  build-wiki.sh
  job-dsl-plugin/pom.xml
  pom.xml
Labels: internal

#1284 Add 1.82 to API viewer
  job-dsl-plugin/pom.xml
  job-dsl-plugin/src/main/hbs/root.hbs
Labels: documentation

#1285 Minor fixups to previous commits
  .github/workflows/wiki.yml
  README.md
Labels: skip-changelog

#1287 Simplify release process
  .github/workflows/wiki.yml
  RELEASING.md
Labels: skip-changelog

#1254 [JENKINS-69500] Add support for Archive Artifacts' `caseSensitive` and `followSymlinks` settings
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ArchiveArtifactsContext.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/wrapper/WrapperContextSpec.groovy
Labels: enhancement

#1288 Bump baseline to 2.387.1
  job-dsl-plugin/pom.xml
  job-dsl-plugin/src/test/resources/expected-dsl.json
  pom.xml
Labels: internal

#1209 Add support for Pipeline Aggregator View
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/DslFactory/pipelineAggregatorView.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/buildHistorySize.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/description.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/filterRegex.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/fontSize.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/onlyLastBuild.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/showBuildDuration.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/useCondensedTables.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/views/PipelineAggregatorView/useScrollingCommits.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/JobParent.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/ViewFactory.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/NestedViewsContext.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/views/PipelineAggregatorView.groovy
  job-dsl-core/src/main/resources/javaposse/jobdsl/dsl/views/PipelineAggregatorView-template.xml
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobParentSpec.groovy
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/views/PipelineAggregatorViewSpec.groovy
Labels: enhancement

#1290 Add 1.83 to API viewer
  job-dsl-plugin/pom.xml
  job-dsl-plugin/src/main/hbs/root.hbs
Labels: documentation

#1293 Suppress false positive warnings
  job-dsl-plugin/src/main/java/javaposse/jobdsl/plugin/DescriptorImpl.java
Labels: skip-changelog

#1298 Add support for "Failure -> Unstable (Test Failures)" trigger
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/ExtendedEmailTriggersContext.groovy
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContextSpec.groovy
Labels: enhancement
