Repository jenkinsci/job-dsl-plugin, pull requests merged in 2024-10, with the labels that each got.

#1474 Require Java 17 or newer
  job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/GlobalJobDslSecurityConfiguration.groovy
  job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/ApiViewerRootAction.groovy
  job-dsl-plugin/src/main/java/javaposse/jobdsl/plugin/DescriptorImpl.java
  job-dsl-plugin/src/test/groovy/javaposse/jobdsl/plugin/GlobalJobDslSecurityConfigurationSpec.groovy
  pom.xml
Labels: internal

#1475 Update Maven
  .github/workflows/api-viewer.yml
  .github/workflows/wiki.yml
Labels: skip-changelog

#1486 Require 2.479.1 LTS or newer
  job-dsl-plugin/pom.xml
  pom.xml
Labels: skip-changelog

#1477 Use monochrome symbol for directory tree
  job-dsl-plugin/src/main/groovy/javaposse/jobdsl/plugin/actions/ApiViewerAction.groovy
  job-dsl-plugin/src/main/resources/images/symbols/directory.svg
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedConfigFilesAction/jobMain.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedConfigFilesBuildAction/summary.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedJobsAction/jobMain.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedJobsBuildAction/summary.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedUserContentsAction/jobMain.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedUserContentsBuildAction/summary.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedViewsAction/jobMain.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/GeneratedViewsBuildAction/summary.jelly
  job-dsl-plugin/src/main/resources/javaposse/jobdsl/plugin/actions/SeedJobAction/jobMain.jelly
  job-dsl-plugin/src/main/webapp/images/directory.svg
Labels: enhancement

#1489 Add 1.90 to API viewer
  job-dsl-plugin/pom.xml
  job-dsl-plugin/src/main/hbs/root.hbs
Labels: documentation
