Repository jenkinsci/job-dsl-plugin, pull requests merged in 2024-08, with the labels that each got.

#1443 Upgrade Node.js to latest LTS
  job-dsl-plugin/package-lock.json
  job-dsl-plugin/pom.xml
Labels: dependencies, javascript

#1444 Build API viewer and Wiki with Java 17
  .github/workflows/api-viewer.yml
  .github/workflows/wiki.yml
Labels: skip-changelog

#1450 Increase baseline to 2.462.x
  job-dsl-plugin/pom.xml
  pom.xml
Labels: internal

#1451 Update Node/NPM
  job-dsl-plugin/package-lock.json
  job-dsl-plugin/pom.xml
Labels: dependencies, javascript

#1416 Improve JCasC docs
  docs/JCasC.md
Labels: documentation

#1415 Make permissions matrix-auth-3.0+ compatible
  README.md
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/Folder/authorization.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/Job/authorization.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/JobAuthorizationContext/permission.groovy
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/JobAuthorizationContext/permissionAll.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/AuthorizationContext.groovy
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/FolderSpec.groovy
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/JobSpec.groovy
Labels: enhancement

#1405 Add support for GitLab Branch Source plugin
  job-dsl-core/src/main/docs/examples/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContext/gitlab.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContext.groovy
  job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/workflow/GitLabBranchSourceContext.groovy
  job-dsl-core/src/test/groovy/javaposse/jobdsl/dsl/helpers/workflow/BranchSourcesContextsSpec.groovy
Labels: enhancement
